// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Fallback satisfies Prisma config typing when DATABASE_URL is unset at build time.
    url:
      process.env.DATABASE_URL ??
      "postgresql://localhost:5432/fundraising_builder?schema=public",
  },
});
